FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
# Allow build-time variables to be accessed
ARG COGNITO_CLIENT_ID
ARG COGNITO_USERPOOL_ID
ARG MONGODB_CONNECTION_STRING
ARG MONGODB_PASSWORD
ARG MORGAN
ARG NODE_ENV
ARG PORT

# Define environment variables
ENV COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
ENV COGNITO_USERPOOL_ID=${COGNITO_USERPOOL_ID}
ENV MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
ENV MONGODB_PASSWORD=${MONGODB_PASSWORD}
ENV MORGAN=${MORGAN}
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}

RUN npm install

RUN npm install -g typescript

COPY . .

RUN npm run build

EXPOSE 8080

CMD ["node", "./dist/index.js"]