name: publich docker image

on:
  push:
    branches: ['dev']

env:
  COGNITO_CLIENT_ID: ${{secrets.COGNITO_CLIENT_ID}}
  COGNITO_USERPOOL_ID: ${{secrets.COGNITO_USERPOOL_ID}}
  MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
  MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
  MORGAN: ${{secrets.MORGAN}}
  NODE_ENV: ${{secrets.NODE_ENV}}
  PORT: ${{secrets.PORT}}

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out to the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/build-push-action@v4
        with:
          images: dhanraj8897/node-microgreens

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}
            COGNITO_USERPOOL_ID=${{ secrets.COGNITO_USERPOOL_ID }}
            MONGODB_CONNECTION_STRING=${{ secrets.MONGODB_CONNECTION_STRING }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
            MORGAN=${{ secrets.MORGAN }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            PORT=${{ secrets.PORT }}
