name: publich docker image

on:
  push:
    branches: ['dev']

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out to the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Create .env file
        run: |
          printf "COGNITO_CLIENT_ID=%s\n" "${{ secrets.COGNITO_CLIENT_ID }}" >> .env
          printf "COGNITO_USERPOOL_ID=%s\n" "${{ secrets.COGNITO_USERPOOL_ID }}" >> .env
          printf "MONGODB_CONNECTION_STRING=%s\n" "${{ secrets.MONGODB_CONNECTION_STRING }}" >> .env
          printf "MONGODB_PASSWORD=%s\n" "${{ secrets.MONGODB_PASSWORD }}" >> .env
          printf "MORGAN=%s\n" "${{ secrets.MORGAN }}" >> .env
          printf "NODE_ENV=%s\n" "${{ secrets.NODE_ENV }}" >> .env
          printf "PORT=%s\n" "${{ secrets.PORT }}" >> .env

      - name: Verify .env file
        run: cat .env

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dhanraj8897/node-microgreens

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
